apiVersion: 1
datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://logistics-clickhouse:8123
    jsonData:
      server: logistics-clickhouse
      port: 8123
      username: admin
      database: logistics
      protocol: http
    secureJsonData:
      password: admin123
    isDefault: true
